### ISSUE TITLE
Please check side effects of this warning 

### ISSUE THREAD

**Issue by sackmotion** [inspireui/mstore-api#1]
Just upgraded to 1.3 from fresh install from GIT , got this warning on each REST API request ,

can you check / fix ? 

[26-Sep-2019 20:08:38 UTC] PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/html/wp-includes/rest-api.php on line 82
[26-Sep-2019 20:08:38 UTC] ** ERROR HANDLER **
[26-Sep-2019 20:08:38 UTC] 2
[26-Sep-2019 20:08:38 UTC] array_merge(): Argument #2 is not an array
[26-Sep-2019 20:08:38 UTC] /var/www/html/wp-includes/rest-api.php
[26-Sep-2019 20:08:38 UTC] 83
[26-Sep-2019 20:08:38 UTC] #0 [internal function]: {closure}(2, 'array_merge(): ...', '/var/www/html/w...', 83, Array)
#1 /var/www/html/wp-includes/rest-api.php(83): array_merge(Array, NULL)
#2 /var/www/html/wp-content/plugins/mstore-api/controllers/MstoreDokan.php(65): register_rest_route('mstore/v1', '/stores', Array)
#3 /var/www/html/wp-includes/class-wp-hook.php(286): MStoreDokan->register_routes_for_handy(Object(WP_REST_Server))
#4 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#6 /var/www/html/wp-includes/rest-api.php(475): do_action('rest_api_init', Object(WP_REST_Server))
#7 /var/www/html/wp-includes/rest-api.php(302): rest_get_server()
#8 /var/www/html/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#9 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#10 /var/www/html/wp-includes/plugin.php(531): WP_Hook->do_action(Array)
#11 /var/www/html/wp-includes/class-wp.php(387): do_action_ref_array('parse_request', Array)
#12 /var/www/html/wp-includes/class-wp.php(737): WP->parse_request('')
#13 /var/www/html/wp-includes/functions.php(1105): WP->main('')
#14 /var/www/html/wp-blog-header.php(16): wp()
#15 /var/www/html/index.php(17): require('/var/www/html/w...')
#16 {main}

I did rollback to mstore-checkout 1.1.7 .

Thank you !

**Comment by sackmotion** [comment]
commit 1270f9c87cbb7f3b2aa6728ca462b083c61a57e5 fixed !

mstore-api 1.3.7 installed , no issues.

Thanks you !
